### ISSUE TITLE
Release Mode App Crash

### ISSUE THREAD

**Issue by eagerashwani** [llSourcell/How_to_Build_a_healthcare_startup#4]
Debug mode app run successfully but release mode app crash

**Comment by AlexandreDewilde** [comment]
Does it work if you build the apk with this command : `flutter build apk --release --target-platform=android-arm64`  ?

**Comment by eagerashwani** [comment]
@allEyezOnCode It work. Thanks

**Comment by Fireballlion** [comment]
Did the app run successfully with the yoga tflite model like the demo?

**Comment by eagerashwani** [comment]
# Yes

**Comment by Fireballlion** [comment]
@therichiekumar Could you please explain how you got the model to work because I am really struggling with it as it just says success but nothing happens. 

Thank you.
