### ISSUE TITLE
Add yoganet compatibility

### ISSUE THREAD

**Issue by AlexandreDewilde** [llSourcell/How_to_Build_a_healthcare_startup#5]
When running yoganet model with the method runmodelonframe() it crashed

**Comment by ankitmaurya001** [comment]
Did you figure it out? Same issue !!

**Comment by AlexandreDewilde** [comment]
@ankitmaurya001 No I didn't, if someone has a solution, I'm interested

**Comment by Omodaka9375** [comment]
Looks like it's some flutter and android studio version issue. I tried 3.5 beta but same error occurred.  Downgrading to AS 2.3 solved it for me.

**Comment by Fireballlion** [comment]
My yoganet model just doesn’t open- the log reads “success” and “resource failed to call close” then doesn’t show anything on screen. Any ideas?

**Comment by Fireballlion** [comment]
It also crashes when I set it as the model to be run on the PoseNet button

**Comment by Fireballlion** [comment]
Hi @Omodaka9375 And I tried the solution listed here, I was using 3.5 and used 2.3.2 but no luck. It says FileNotFound: yoganet.tflite. I have tried adding the file to the pubspec.yaml but it doesn’t fix the issue. any ideas?
